---
title: "Winter2020Lab1"
author: "Brock Rowley, Akhila Nekkanti, Claire Matese"
date: "1/8/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load}
library(tidyverse)
library(rio)
library(lubridate)
library(here)
library(dplyr)
library(forcats)

rstats <- rio::import(here::here("data", "rstats_tweets.rds"))
View(rstats)
```

```{r commit2}
rstats_count <- rstats %>% 
  select(screen_name, created_at, status_id) %>% 
  # mutate(status_id = as.numeric(status_id)) %>% 
  # group_by(screen_name) %>% 
  count(screen_name) %>% 
  arrange(desc(n)) %>% 
  mutate(screen_name = as.factor(screen_name)) %>% 
  slice(1:25)

rstats2 <- rstats_count %>% 
  mutate(screen_name = fct_reorder(screen_name, n))
  
name_graph <- ggplot(rstats2, aes(screen_name, n)) +
  #geom_col() +
  coord_flip()
  
name_graph +
  geom_col()
```

```{r commit3}
name_graph +
  geom_col(fill = "#7CA0E9", alpha = .8) +
  theme_minimal() +
  labs(x = "Twitter Screen Name", 
       y = "Count", 
       title = "Most prolific #rstats tweeters", subtitle = "Top 25 screen names displayed",
       caption = "Data from Mike Kearny, distributed via #tidytuesday")
```

```{r commit4}
month_rstats <- rstats %>%
  mutate(month = round_date(created_at, "month")) %>%
  filter(month < as_datetime("2019-01-01 00:00:00")) %>% 
  count(month)

month_graph <- ggplot(month_rstats, aes(month, n)) +
  geom_line()
  
month_graph 
```

```{r commit5}
month_graph +
   geom_ribbon(aes(ymin = 0, ymax = n), fill = "#D3DFF8", alpha = .5) +
  geom_smooth(se = FALSE, color = "#EB57F8") +
  theme_minimal() +
  labs(x = "Year (data summarized by month)", 
       y = "Number of #stats tweets", 
       title = "Growth of the #rstats hashtag on twitter over time", 
       caption = "Data from Mike Kearny, distributed via #tidytuesday")
```
